menu:
    Blog: /
    Archive: /archives/
    About: /about/
    GitHub: https://github.com/phbai
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: marisas-blog
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2016
